"""
PowerSense AI — Electricity Bill Transparency & Complaint Assistant
====================================================================
A Pakistan-focused AI application that helps consumers understand their
electricity bills: which parts are energy charges, taxes, surcharges,
adjustments, or arrears — and which parts may need verification with the
DISCO or NEPRA.

This app is informational only. It never labels a charge as illegal,
fake, or fraudulent — see the disclaimer in the sidebar and About page.
"""

import os
import json
import streamlit as st

from rag_utils import (
    GROQ_MODEL,
    extract_bill_text,
    build_or_load_vectorstore,
    retrieve_relevant_chunks,
    extract_bill_fields_with_llm,
    analyze_and_verify_bill,
    generate_complaint_package,
    BILL_FIELDS_SCHEMA,
)

# ---------------------------------------------------------------------------
# STATIC / VERIFIED CONSTANTS (never generated by the LLM)
# ---------------------------------------------------------------------------

DISCOS = [
    "Auto-detect", "FESCO", "LESCO", "GEPCO", "MEPCO", "IESCO",
    "PESCO", "HESCO", "SEPCO", "QESCO", "K-Electric", "Other",
]

CONSUMER_CATEGORIES = ["Residential", "Commercial", "Industrial", "Other"]
LANGUAGES = ["English", "Urdu", "Roman Urdu"]

# Official NEPRA consumer complaint portal (verified public URL — do not
# let the LLM generate or alter this link).
NEPRA_COMPLAINT_URL = "https://www.nepra.org.pk/Complaint.php"

DISCLAIMER_TEXT = (
    "PowerSense AI provides informational bill analysis based on the uploaded bill and "
    "available official reference documents. It does not replace official tariff "
    "determinations or legal advice. Charges marked for verification should be confirmed "
    "with the relevant electricity provider or regulatory authority."
)

STATUS_ICONS = {
    "Explained": "🟢",
    "Applicable": "🟢",
    "Requires Verification": "🟡",
    "Potential Billing Issue": "🔴",
}

NUMERIC_FIELDS = [
    "units_consumed", "previous_reading", "current_reading",
    "previous_bill_amount", "current_bill_amount", "amount_payable",
    "electricity_charges", "taxes", "surcharges", "fca",
    "quarterly_adjustment", "fixed_charges", "arrears", "other_charges",
]

TEXT_FIELDS = [
    "consumer_number", "meter_number", "provider", "billing_month",
    "issue_date", "due_date", "tariff_category",
]

FIELD_LABELS = {
    "consumer_number": "Consumer/Reference Number",
    "meter_number": "Meter Number",
    "provider": "Provider/DISCO",
    "billing_month": "Billing Month",
    "issue_date": "Issue Date",
    "due_date": "Due Date",
    "previous_reading": "Previous Meter Reading",
    "current_reading": "Current Meter Reading",
    "units_consumed": "Units Consumed (kWh)",
    "tariff_category": "Tariff Category",
    "previous_bill_amount": "Previous Bill Amount (PKR)",
    "current_bill_amount": "Current Bill Amount (PKR)",
    "amount_payable": "Amount Payable (PKR)",
    "electricity_charges": "Electricity/Energy Charges (PKR)",
    "taxes": "Taxes / GST (PKR)",
    "surcharges": "Surcharges (PKR)",
    "fca": "Fuel Charges Adjustment - FCA (PKR)",
    "quarterly_adjustment": "Quarterly Tariff Adjustment (PKR)",
    "fixed_charges": "Fixed Charges (PKR)",
    "arrears": "Arrears / Previous Dues (PKR)",
    "other_charges": "Other Charges (PKR)",
}


# ---------------------------------------------------------------------------
# PAGE CONFIG + STYLE
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="PowerSense AI",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
    <style>
    .main { background-color: #0e1117; }
    .stMetric { background-color: #161b22; padding: 10px; border-radius: 10px; }
    .status-badge {
        display: inline-block; padding: 2px 10px; border-radius: 12px;
        font-size: 0.85rem; font-weight: 600; margin-right: 6px;
    }
    .disclaimer-box {
        background-color: #1c1f26; border-left: 4px solid #f0b400;
        padding: 10px 14px; border-radius: 6px; font-size: 0.85rem;
        color: #d0d0d0; margin-bottom: 10px;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


def init_state():
    defaults = {
        "errors": [],
        "bill_text": "",
        "bill_data": None,
        "analysis": None,
        "complaint": None,
        "context_chunks": [],
    }
    for k, v in defaults.items():
        if k not in st.session_state:
            st.session_state[k] = v


init_state()


# ---------------------------------------------------------------------------
# SIDEBAR — INPUTS
# ---------------------------------------------------------------------------

with st.sidebar:
    st.markdown("## ⚡ PowerSense AI")
    st.caption("Electricity Bill Transparency & Complaint Assistant")

    st.markdown('<div class="disclaimer-box">' + DISCLAIMER_TEXT + "</div>", unsafe_allow_html=True)

    api_key = st.secrets.get("GROQ_API_KEY", os.environ.get("GROQ_API_KEY", ""))
    if not api_key:
        st.warning(
            "GROQ_API_KEY is not set. Add it under Streamlit Cloud → App settings → "
            "Secrets (or as an environment variable locally) to enable AI analysis."
        )

    st.markdown("### Bill Details")
    provider_choice = st.selectbox("Electricity Provider / DISCO", DISCOS, index=0)
    consumer_category = st.selectbox("Consumer Category", CONSUMER_CATEGORIES, index=0)
    language = st.selectbox("Response Language", LANGUAGES, index=0)

    user_question = st.text_area(
        "Your question (optional)",
        placeholder="Why is my electricity bill so high? / Explain all taxes and extra charges.",
        height=80,
    )

    st.markdown("---")
    st.caption(f"Model: `{GROQ_MODEL}` via Groq API")


# ---------------------------------------------------------------------------
# TABS / PAGES
# ---------------------------------------------------------------------------

tabs = st.tabs([
    "🏠 Home", "📤 Upload Bill", "🔍 Analyze Bill", "📊 Bill Breakdown",
    "⚠️ Attention", "💡 Why High?", "📢 Complaint Assistant",
    "📚 Sources", "ℹ️ About",
])

(tab_home, tab_upload, tab_analyze, tab_breakdown, tab_attention,
 tab_why_high, tab_complaint, tab_sources, tab_about) = tabs


# ------------------------------- HOME --------------------------------------
with tab_home:
    st.title("⚡ PowerSense AI")
    st.subheader("Understand your electricity bill — clearly, honestly, and without guesswork.")
    col1, col2, col3 = st.columns(3)
    col1.metric("Step 1", "Upload your bill")
    col2.metric("Step 2", "AI analyzes each charge")
    col3.metric("Step 3", "Get clear answers")
    st.markdown(
        """
        PowerSense AI reads your electricity bill (photo, screenshot, or PDF) and explains,
        in plain language, exactly where your money is going:

        - ⚡ Electricity/energy charges based on your units consumed
        - 🧾 Taxes, duties, and surcharges
        - 🔄 FCA (Fuel Charges Adjustment) and quarterly tariff adjustments
        - 📌 Fixed charges, arrears, and other line items
        - 🟡 Items that need verification with your provider or NEPRA

        Go to **📤 Upload Bill** to get started.
        """
    )
    if st.session_state["errors"]:
        with st.expander("⚠️ Notices from this session"):
            for e in st.session_state["errors"][-10:]:
                st.write("- " + e)


# ------------------------------ UPLOAD --------------------------------------
with tab_upload:
    st.header("📤 Upload Your Electricity Bill")
    uploaded_file = st.file_uploader(
        "Upload a photo/screenshot (JPG, JPEG, PNG) or a PDF of your bill",
        type=["jpg", "jpeg", "png", "pdf"],
    )

    if uploaded_file is not None:
        with st.spinner("Reading your bill (OCR / PDF extraction)..."):
            text = extract_bill_text(uploaded_file)
            st.session_state["bill_text"] = text

        if uploaded_file.type.startswith("image"):
            st.image(uploaded_file, caption="Uploaded bill", use_container_width=True)

        if st.session_state["bill_text"]:
            st.success("Text extracted from your bill. Review it below if you like.")
            with st.expander("🔎 Raw extracted text (for verification)"):
                st.text(st.session_state["bill_text"][:5000])
        else:
            st.error(
                "We could not confidently extract text from this file. "
                "Please try a clearer photo/PDF, or fill in details manually in the "
                "'Analyze Bill' tab."
            )

    st.markdown("---")
    st.info(
        "No sensitive personal information (CNIC, phone number, address) is required. "
        "Only bill-related figures are used for analysis."
    )


# ------------------------------ ANALYZE -------------------------------------
with tab_analyze:
    st.header("🔍 Analyze Bill")

    if not api_key:
        st.error("Add your GROQ_API_KEY in Streamlit Secrets to run the analysis.")

    run_extraction = st.button(
        "🧠 Step 1: Extract Fields from Bill Text", disabled=not st.session_state["bill_text"] or not api_key
    )

    if run_extraction:
        with st.spinner("Bill Extraction Agent is reading your bill..."):
            data = extract_bill_fields_with_llm(api_key, st.session_state["bill_text"])
            # Fill provider automatically if detected and user left it as Auto-detect
            if provider_choice == "Auto-detect" and data.get("provider"):
                pass  # keep LLM-detected provider string as-is in bill_data
            st.session_state["bill_data"] = data
        st.success("Fields extracted. Review and correct them below if needed.")

    if not st.session_state["bill_text"]:
        st.warning("Please upload a bill in the '📤 Upload Bill' tab first.")

    st.markdown("### ✍️ Review / Complete Bill Fields")
    st.caption("Any field the AI could not confidently read is left blank — please fill it in.")

    bill_data = st.session_state["bill_data"] or {f: None for f in BILL_FIELDS_SCHEMA}
    edited = {}

    with st.form("bill_fields_form"):
        cols = st.columns(2)
        for i, field in enumerate(BILL_FIELDS_SCHEMA):
            col = cols[i % 2]
            label = FIELD_LABELS.get(field, field)
            current_value = bill_data.get(field)
            if field in NUMERIC_FIELDS:
                val = col.number_input(
                    label,
                    value=float(current_value) if isinstance(current_value, (int, float)) else 0.0,
                    step=1.0,
                    key=f"field_{field}",
                )
                edited[field] = val if val != 0.0 else None
            else:
                val = col.text_input(
                    label,
                    value=str(current_value) if current_value else "",
                    key=f"field_{field}",
                )
                edited[field] = val or None

        submitted = st.form_submit_button("💾 Save Bill Details")
        if submitted:
            # Resolve provider: prefer manually selected DISCO unless Auto-detect
            if provider_choice != "Auto-detect":
                edited["provider"] = provider_choice
            st.session_state["bill_data"] = edited
            st.success("Bill details saved.")

    st.markdown("---")
    run_analysis = st.button(
        "🚀 Step 2: Run Full Bill Analysis (Tariff + Verification)",
        disabled=not st.session_state["bill_data"] or not api_key,
    )

    if run_analysis:
        final_bill_data = st.session_state["bill_data"]
        query_text = (
            f"{final_bill_data.get('tariff_category') or ''} tariff "
            f"{final_bill_data.get('provider') or provider_choice} "
            f"units {final_bill_data.get('units_consumed') or ''} "
            f"FCA quarterly adjustment surcharges taxes {user_question or ''}"
        )
        with st.spinner("Retrieving official tariff/rule context (RAG)..."):
            vectorstore = build_or_load_vectorstore()
            context_chunks = retrieve_relevant_chunks(query_text, vectorstore)
            st.session_state["context_chunks"] = context_chunks

        with st.spinner("Tariff Analysis & Charge Verification Agents are working..."):
            resolved_provider = (
                final_bill_data.get("provider") if provider_choice == "Auto-detect" else provider_choice
            )
            analysis = analyze_and_verify_bill(
                api_key,
                final_bill_data,
                resolved_provider or "Unknown",
                consumer_category,
                language,
                context_chunks,
            )
            st.session_state["analysis"] = analysis

        if analysis:
            st.success("Analysis complete! See the 📊 Bill Breakdown, ⚠️ Attention, and 💡 Why High? tabs.")
        else:
            st.error(
                "The AI analysis could not be completed (Groq API issue or unexpected response). "
                "Please check your API key and try again."
            )


# ---------------------------- BREAKDOWN -------------------------------------
with tab_breakdown:
    st.header("📊 Bill Breakdown")
    analysis = st.session_state["analysis"]

    if not analysis:
        st.info("Run the analysis in the '🔍 Analyze Bill' tab to see your breakdown here.")
    else:
        summary = analysis.get("bill_summary", {})
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Provider", summary.get("provider") or "—")
        c2.metric("Billing Month", summary.get("billing_month") or "—")
        c3.metric("Units Consumed", summary.get("units_consumed") or "—")
        c4.metric("Total Bill (PKR)", summary.get("total_bill") or "—")
        st.caption(f"Due date: {summary.get('due_date') or '—'}")

        st.markdown("### Charge Breakdown")
        breakdown = analysis.get("charge_breakdown", [])
        if breakdown:
            st.markdown(
                "| Component | Amount (PKR) | Status | Explanation |\n"
                "|---|---:|---|---|\n" +
                "\n".join(
                    f"| {row.get('component','—')} | {row.get('amount') if row.get('amount') is not None else '—'} "
                    f"| {STATUS_ICONS.get(row.get('status',''), '')} {row.get('status','—')} "
                    f"| {row.get('explanation','—')} |"
                    for row in breakdown
                )
            )
        else:
            st.warning("No charge components were detected in the bill data.")

        st.markdown("### 📈 Consumption Analysis")
        consumption = analysis.get("consumption_analysis", {})
        if consumption:
            cc1, cc2, cc3, cc4 = st.columns(4)
            cc1.metric("Previous Units", consumption.get("previous_units") or "—")
            cc2.metric("Current Units", consumption.get("current_units") or "—")
            cc3.metric("Difference", consumption.get("difference") or "—")
            cc4.metric("% Change", consumption.get("percent_change") or "—")
            st.caption(consumption.get("note", ""))


# ---------------------------- ATTENTION -------------------------------------
with tab_attention:
    st.header("⚠️ Charges That Need Your Attention")
    analysis = st.session_state["analysis"]

    if not analysis:
        st.info("Run the analysis first to see flagged items here.")
    else:
        items = analysis.get("attention_items", [])
        if not items:
            st.success("🟢 No charges were flagged as unclear or requiring verification.")
        for item in items:
            icon = STATUS_ICONS.get(item.get("status", ""), "🟡")
            with st.expander(f"{icon} {item.get('charge_name','Unknown Charge')} — PKR {item.get('amount','—')}"):
                st.write(f"**Status:** {item.get('status','Requires Verification')}")
                st.write(f"**Why flagged:** {item.get('flag_reason','—')}")
                st.write(f"**Source used:** {item.get('source_used') or 'No specific official document matched'}")
                st.write(f"**What to verify:** {item.get('what_to_verify','—')}")


# ---------------------------- WHY HIGH --------------------------------------
with tab_why_high:
    st.header("💡 Why Is My Bill High?")
    analysis = st.session_state["analysis"]
    if not analysis:
        st.info("Run the analysis first to see this explanation.")
    else:
        st.write(analysis.get("why_bill_is_high", "No explanation was generated."))


# ---------------------------- COMPLAINT -------------------------------------
with tab_complaint:
    st.header("📢 Complaint Assistant")
    analysis = st.session_state["analysis"]
    bill_data = st.session_state["bill_data"]

    if not analysis or not bill_data:
        st.info("Run the analysis first so the complaint assistant has context to work with.")
    else:
        if st.button("📢 I Want to File a Complaint"):
            with st.spinner("Complaint Assistant Agent is preparing your complaint package..."):
                resolved_provider = (
                    bill_data.get("provider") if provider_choice == "Auto-detect" else provider_choice
                )
                complaint = generate_complaint_package(
                    api_key, bill_data, analysis, resolved_provider or "Unknown", language
                )
                st.session_state["complaint"] = complaint

        complaint = st.session_state["complaint"]
        if complaint:
            st.subheader("1️⃣ Should you consider a complaint?")
            st.write("Yes" if complaint.get("should_consider_complaint") else "Not clearly necessary right now")
            st.write(complaint.get("reason_summary", ""))

            st.subheader("2️⃣ Likely Complaint Category")
            st.write(complaint.get("likely_complaint_category", "—"))

            st.subheader("3️⃣ Evidence You Should Keep")
            for e in complaint.get("evidence_to_keep", []):
                st.write("- " + e)

            st.subheader("4️⃣ Draft Complaint Description")
            st.text_area("You can copy/edit this before submitting:",
                         value=complaint.get("draft_complaint_text", ""), height=150)

            st.subheader("5️⃣ Contact Your Provider First")
            st.write(complaint.get("contact_provider_first_note",
                                    "It is generally advisable to contact your DISCO's helpline/office first."))

            st.subheader("6️⃣ Official Complaint Portal")
            st.link_button("🔗 Open NEPRA Complaint Portal", NEPRA_COMPLAINT_URL)
            st.caption(
                "This is an official, verified link. PowerSense AI does not generate or "
                "alter complaint URLs."
            )
            st.info(
                "Filing a complaint does not guarantee any specific outcome. NEPRA/your DISCO "
                "will review the evidence and make their own determination."
            )


# ---------------------------- SOURCES ---------------------------------------
with tab_sources:
    st.header("📚 Sources Used")
    chunks = st.session_state["context_chunks"]
    analysis = st.session_state["analysis"]

    sources_used = set()
    if analysis:
        sources_used.update(analysis.get("sources_used", []) or [])
    sources_used.update(c["source"] for c in chunks)

    if not sources_used:
        st.warning(
            "No knowledge-base documents were used for this analysis. "
            "Add official PDFs (tariff schedules, NEPRA notifications, FCA/QTA decisions, "
            "complaint procedures) to the `knowledge/` folder to enable source-backed answers."
        )
    else:
        for s in sorted(sources_used):
            st.write(f"📄 {s}")

    with st.expander("🔍 Retrieved context (raw chunks used for this analysis)"):
        for c in chunks:
            st.markdown(f"**Source: {c['source']}**")
            st.caption(c["text"][:500])
            st.markdown("---")


# ------------------------------ ABOUT ---------------------------------------
with tab_about:
    st.header("ℹ️ About PowerSense AI")
    st.markdown(
        """
        **PowerSense AI** is a hackathon project that helps Pakistani electricity consumers
        understand their bills using Retrieval-Augmented Generation (RAG) and the Groq LLM API.

        **How it works:**
        1. You upload a photo/PDF of your bill.
        2. OCR / PDF text extraction pulls out the raw text.
        3. A Bill Extraction Agent structures the bill into fields.
        4. A Tariff Analysis Agent retrieves relevant official documents from the knowledge base.
        5. A Charge Verification Agent classifies each charge as Explained, Applicable,
           Requires Verification, or Potential Billing Issue.
        6. A Complaint Assistant Agent helps you prepare a complaint if needed, and links to the
           official NEPRA complaint portal.

        **What this app is NOT:**
        - It is not a legal authority and cannot confirm whether a charge is illegal.
        - It does not fabricate tariff rates — anything not backed by the knowledge base is
          marked as "Requires Verification".
        - It does not store your bill data outside of your current session.
        """
    )
    st.markdown('<div class="disclaimer-box">' + DISCLAIMER_TEXT + "</div>", unsafe_allow_html=True)
